<?php



$includedPages = [
    'catalogsearch_result_index',
    'catalog_category_view',
    'wishlist_index_index',
    'cms_index_index',
    'catalog_product_view'
];
?>


<style type="text/css">
.show-prices-handler .price-box .price {
    display: block;
}
.price-box .price{
  display: none;
}
</style>

<?php
    $category = $block->getCurrentCategory();

    $productBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\ListProduct');
    $page = ($block->escapeHtml($productBlock->getRequest()->getParam('p')) ? $block->escapeHtml($productBlock->getRequest()->getParam('p')) : 1);
    $limit = ($block->escapeHtml($productBlock->getRequest()->getParam('product_list_limit')) ? $block->escapeHtml($productBlock->getRequest()->getParam('product_list_limit')) : 24);
?>


<div id="clorasPrice"></div>
<div id="clorasInventory"></div>
<script type="text/x-magento-init">
    {
        "#clorasPrice": {
            "Cloras_Base/price":{ "priceUrl" : "<?= $block->escapeUrl($this->getBasePriceUrl()); ?>", 
            "page": "<?= $block->escapeHtml($page); ?>", "limit": "<?= $block->escapeHtml($limit); ?>", "loaderImg" : "<?= $productBlock->getViewFileUrl('images/loader-1.gif') ?>"}

        },
        "#clorasInventory": {
            "Cloras_Base/inventory":{ "inventoryUrl" : "<?= $block->escapeUrl($this->getBaseInventoryUrl()); ?>","page": "<?= $block->escapeHtml($page); ?>", "limit": "<?= $block->escapeHtml($limit); ?>", "loaderImg" : "<?= $productBlock->getViewFileUrl('images/loader-1.gif') ?>"}

        }
    }        
</script>


<script type="text/javascript">

    
    require(["jquery"],function($) {
        $('.pages-items li.item a.page, .toolbar #limiter').click(function() {
                $('body').addClass('show-prices-handler');
            });
    });

</script>



