<?php $product = $block->getCurrentProduct();
if ($product->getTypeId() == 'configurable') {
    $uomData = $block->getUOMData();
    $optionAttr = $product->getTypeInstance()->getConfigurableAttributesAsArray($product);
    $data = $product->getTypeInstance()->getConfigurableOptions($product);
    $options = [];
    foreach ($data as $attr) {
        foreach ($attr as $p) {
            $options[$p['sku']][$p['attribute_code']] = $p;
        }
    }
    $addToCartUrl = $block->getUrl('Catalog/index/addtocart');
    $childProducts = $product->getTypeInstance()->getUsedProducts($product);
    if (!empty($childProducts)) { ?>
<div class="product-add-form-new">
    <form action="<?= $addToCartUrl; ?>" method="post" id="product_addtocart_form-new" novalidate="novalidate">
        <input type="hidden" name="product" value="<?= $block->escapeHtml($product->getId()); ?>">
        <input type="hidden" name="selected_configurable_option" value="">
            <?= $block->getBlockHtml('formkey')?>
        <div class="products wrapper">
            <table class="product_mdstable" id="super-product-table" >
            <caption>product add form</caption>
                <tbody>
                <tr>
                    <th scope="row">SKU</th>
                    <th scope="row">Name</th>
                    <th scope="row">Variants</th>
                    <th scope="row">Availability</th>
                    <th scope="row">
                        <span>
                            <select name="variant_uom" id="variant-uom">
                                <?php if (is_array($uomData) && isset($uomData['uomFactors']) && !empty($uomData['uomFactors'])) { ?>
                                    <?php foreach ($uomData['uomFactors'] as $uom) { ?>
                                        <option value="<?= $block->escapeHtml($uom['altUomCode']); ?>">
                                            <?php if ($uom['altUomCode'] != '') {
                                                echo $block->escapeHtml($uom['altUomCode']);
                                            } else {
                                                echo $block->escapeHtml($uom['altUomDesc']);
                                            } ?></option>
                                    <?php }
                                } else { ?>
                                <option value="EA">EACH</option>
                                <?php } ?>
                            </select>
                        </span>
                        Add To Cart</th>
                </tr>
                    <?php foreach ($childProducts as $childProduct) {
                        $erpData = $block->getErpProductData($childProduct->getSku()); ?>
                    <tr>
                        <td>
                            <span class="data-th" style="display: none;">SKU</span>
                            <strong><?= $block->escapeHtml($childProduct->getSku()); ?></strong>
                        </td>
                       <td class="item-specification"><span class="data-th" style="display: none;">Name</span>
                        <?= $block->escapeHtml($childProduct->getName()); ?>
                        </td>
                        <td><span class="data-th" style="display: none;">Variants</span>
                            <?php if (!empty($options[$childProduct->getSku()])) {
                                foreach ($options[$childProduct->getSku()] as $option) {
                                    echo '<p>'.$block->escapeHtml($option['attribute_code']).': <b>'.$block->escapeHtml($option['option_title']).'</b></p>';
                                }
                            } ?></td>
                        <td class="inventory-availability">
                        <span class="data-th" style="display: none;">Availability</span>
                            <?php if (isset($erpData['lineItem']['locations'])) { ?>
                                <ul>
                                    <?php foreach ($erpData['lineItem']['locations'] as $qtyData) {
                                        if ($qtyData['branchName'] != '') { ?>
                                            <li><?= $block->escapeHtml($qtyData['branchName']) . ': <b>' . $block->escapeHtml($qtyData['available']).'</b>'; ?><?php if ((int)$qtyData['available'] > 0) {
                                                echo '<span> In Stock</span>';
                                                } else {
                                                    echo '<span> Out of Stock</span>';
                                                } ?></li>
                                        <?php }
                                    } ?>
                                </ul>
                            <?php } else { ?>
                                <p class="in-stock"><span> In Stock</span></p>
                            <?php } ?>
                        </td>
                        <td class="add-to-cart-wrapper-plp">
                            <span class="data-th" style="display: none;">Add To Cart</span>
                            <div class="box-tocart">
                                <div class="cart-section">
                                    <?php
                                    foreach ($optionAttr as $key => $optionv) {
                                        $hiddenInput = 'super_attr['.$childProduct->getId().']['.$key.']'; ?>
                                        <input type="hidden" name="<?= $block->escapeHtml($hiddenInput); ?>" value="<?= $block->escapeHtml($childProduct->getData($optionv['attribute_code'])); ?>" />
                                    <?php } ?>
                                    <input type="number" name="<?= 'super_attr_qty['.$block->escapeHtml($childProduct->getId()).']'; ?>" value="0" title="Qty" class="input-text qty" />
                                </div>
                                <div class="price-list"><strong><?php if (isset($erpData['prices']['netPrice'])) {
                                    echo $block->escapeHtml($block->getPriceWithCurrency($erpData['prices']['netPrice']));
                                                                } else {
                                                                    echo $block->escapeHtml($block->getPriceWithCurrency($childProduct->getPrice()));
                                                                } ?></strong><span class="price-uom">/EA</span></div>
                            </div>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <button type="submit" class="primary">Add To Cart</button>
    </form>
</div>
    <?php } ?>
<script>
    require([
        "jquery"
    ], function ($) {
        $(document).ready(function () {
            $('.catalog-product-view .product-add-form form#product_addtocart_form').remove();
        });
    });
</script>
<?php } ?>
